version: '3.8'

services:
  local-rag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      # 在这里可以设置环境变量，例如：
      # - PYTHONUNBUFFERED=1
      # - LOG_LEVEL=info
      - APP_ENV=production
